language: go
sudo: false
arch:
- amd64
- ppc64le
go:
- "1.16"
- "1.23"

install:
- go get -t ./...
- go get github.com/mattn/goveralls

script:
- go fmt ./...
- go vet ./...
- go test -v
- go test -v --race
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile coverage.out -service travis-ci
